language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pyflakes
  # Deal with issue on Travis builders re: multiprocessing.Queue :(
  - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
# command to run tests
script:
  - make unit functional
  # Check that there are no syntax errors
  - find lettuce -type f -name "*.py" -print | xargs python -m py_compile
  - find lettuce -type f -name "*.py" -print | xargs pyflakes
